### PR TITLE
Added activity splits support

### PR DESCRIPTION
**Pull request by AndreaLaperuta**
Hi Gabor, 

I simply added splits support on activity

Andrea

### CODE REVIEW

**Comment by AndreaLaperuta** [comment]
Also added photo info in activity

**Comment by gabornemeth** [comment]
Looks good! 👍 
Could you add tests for verifying the successful parsing of splits and photos from the sample json?

**Comment by AndreaLaperuta** [comment]
Test added 👍

**Comment by gabornemeth** [comment]
@Laperuta  Could you add sample JSON activities response as a resource to the test project and verify the splits and photos info getting parsed? The tests executed against my activities on the build server does not verify them, as those activities are cycling and don't contain any photo. I'll try to improve the online test activities.
You have to rebase/merge the actual master branch too.
Thank you.

**Comment by gabornemeth** [comment]
Rebased in #35

**Pull request closed without merging**
