### PR TITLE
Interfaced version

### PR DESCRIPTION
**Pull request by OracPrime**
This PR is for an interfaced version (to allow mocking) with revamped testing (to allow anyone to run at least a subset of the tests, with authentication via an Azure Function).

I don't imagine for a moment that the changes in the areas I've looked at are complete, but I think they are better than what went before.

This PR is therefore as much a call for suggestions as it is a PR to take the code forward.

### CODE REVIEW

**Comment by OracPrime** [comment]
bump

**Comment by gabornemeth** [comment]
I have already cleaned up these changes [into a new branch](https://github.com/gabornemeth/StravaSharp/tree/interfaced-version). It's time to re-align it again though.

I like the concept generally, but don't like some parts, e.g. relying on an external server-side component (for simulating Strava API, or getting access token, etc.) I don't like maintaining a Strava account for testing either, which I have started with and still plays a role in tests. I think for testability the best would be to create a fake client that returns baked in JSON responses. This is enough for tests and easy to maintain, only possible drawback is we can't test against real Strava API real time - i would not do it anyway 😄 If some problem occurs, the response from Strava API can be used fix it with new or modified test cases.

**Comment by OracPrime** [comment]
I did have my doubts about the external server-side component and live-testing against a test athlete.  However I went for it because

 

a.	No-one *has* to run those tests.  I wouldn’t make them part of the continuous integration process for example.
b.	You can test against them defensively.  E.g. testing that the number of segments in a ride is >=24 rather than =24, since people might add new segments to make the count go up.

 

I’d be disappointed if the live testing didn’t make the merge, but I’d understand if all the tests had an [Explicit] attribute.

 

DC

**Comment by OracPrime** [comment]
You branch seems to be a good merge of mine.  Is there anything (apart from the compatibility breakage, of course) stopping this being merged to master?

I have other bits I'm keen to add - in particular a caching front end - and I'll get started branching from my interfaced branch, but I'd rather branch from master!

**Comment by gabornemeth** [comment]
I'm changing some test cases - which are hard to run against real data on Strava - by simulating the response from the API. Good samples can be grabbed from the Strava API documentation itself. It is quite easy to only make this part interfaced and implemented differently in test code.

**Pull request closed without merging**
